FROM mcr.microsoft.com/dotnet/core/sdk:2.2-alpine AS build
WORKDIR /app

# copy csproj and restore as distinct layers
#COPY *.sln .
COPY svc/*.csproj ./svc/
WORKDIR /app/svc
RUN dotnet restore

# copy everything else and build app
COPY svc/. ./
RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine AS runtime
WORKDIR /app
EXPOSE 80
COPY --from=build /app/svc/out ./
ENTRYPOINT ["dotnet", "Tehk.Sourcers.Meetup.Svc.dll"]